sudo: required
services:
    - docker

before_install: #telling travis what to do before starting the test
    - docker build -t surya3/docker-react -f Dockerfile.dev .


script:   #telling travis to run the following test/tests
    - docker run -e CI=true surya3/docker-react npm run test 